version: '3.8'

services:
  spring-db:
    image: postgres:15
    container_name: zelephant
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: spring_postgres
      POSTGRES_DB: zelephant
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
